### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wanz1594** [6nz/anti-vm#1]
I added the webhook, but when I open it, it doesn't show anything.

**Comment by 6nz** [comment]
Hello

**Comment by 6nz** [comment]
This repo is not maintained anymore

**Comment by 6nz** [comment]
Please check this project: https://github.com/xFGhoul/PythonProtector

**Comment by 6nz** [comment]
thats the new anti-vm / python protection system

**Comment by Wanz1594** [comment]
> thats the new anti-vm / python protection system

tysm

**Comment by Wanz1594** [comment]
uhhh, Can you show me how to use it?

**Comment by samogost** [comment]
> thats the new anti-vm / python protection system

How can I add this Anti-VM to my virus file?

**Comment by 6nz** [comment]
Check the example usage

**Comment by 6nz** [comment]
![Uploading Screenshot_2023-01-23-16-55-31-263-edit_com.android.chrome.jpg…]()

**Comment by 6nz** [comment]
![Screenshot_2023-01-23-16-55-31-263-edit_com android chrome](https://user-images.githubusercontent.com/74118308/214085922-440b24d4-a4cc-4935-9e16-abed1ec798ae.jpg)

**Comment by Wanz1594** [comment]
> ![Screenshot_2023-01-23-16-55-31-263-edit_com android chrome](https://user-images.githubusercontent.com/74118308/214085922-440b24d4-a4cc-4935-9e16-abed1ec798ae.jpg)

Ok

**Comment by samogost** [comment]
> ![Screenshot_2023-01-23-16-55-31-263-edit_com android chrome](https://user-images.githubusercontent.com/74118308/214085922-440b24d4-a4cc-4935-9e16-abed1ec798ae.jpg)



> ![Screenshot_2023-01-23-16-55-31-263-edit_com android chrome](https://user-images.githubusercontent.com/74118308/214085922-440b24d4-a4cc-4935-9e16-abed1ec798ae.jpg)

I'm not good at python so I hope you can help. What is Setup.py used for?

**Comment by 6nz** [comment]
You don't have to download the files

**Comment by 6nz** [comment]
Thats a python module

**Comment by 6nz** [comment]
You can import it to your script by using import pyprotector

**Comment by 6nz** [comment]
Read the readme file

**Comment by samogost** [comment]
> ![Screenshot_2023-01-23-16-55-31-263-edit_com android chrome](https://user-images.githubusercontent.com/74118308/214085922-440b24d4-a4cc-4935-9e16-abed1ec798ae.jpg)



> Read the readme file

Wanz1594 is my sub account to avoid acc ban due to vps creation

I will try

**Comment by samogost** [comment]
> Read the readme file

Traceback (most recent call last):
  File "C:\Users\administrator\Downloads\main.py", line 4, in <module>
    from pyprotector import PythonProtector
  File "C:\hostedtoolcache\windows\Python\3.11.1\x64\Lib\site-packages\pyprotector\__init__.py", line 12, in <module>
    from .protector import PythonProtector
  File "C:\hostedtoolcache\windows\Python\3.11.1\x64\Lib\site-packages\pyprotector\protector.py", line 27, in <module>
    from .constants import ProtectorInfo, LoggingInfo, EmbedConfig, Valid
  File "C:\hostedtoolcache\windows\Python\3.11.1\x64\Lib\site-packages\pyprotector\constants.py", line 20, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

Hmm

**Comment by samogost** [comment]
> Read the readme file

uhh

**Comment by 6nz** [comment]
Did you install the requires modules?

**Comment by samogost** [comment]
> Did you install the requires modules?

I did, 

> Did you install the requires modules?

just running this cmd command is enough right? `py -3 -m pip install -U PythonProtector`

**Comment by 6nz** [comment]
> > Did you install the requires modules?
> 
> I did,
> 
> > Did you install the requires modules?
> 
> just running this cmd command is enough right? `py -3 -m pip install -U PythonProtector`

yes

**Comment by 6nz** [comment]
if you are getting ModuleNotFoundError: No module named 'cryptography'

**Comment by samogost** [comment]
> try: pip uninstall cryptography pip install cryptography

I'll try it later, and if it works, I'll ask more about how it works.

**Comment by samogost** [comment]
> try: pip uninstall cryptography pip install cryptography

If It works and can stop the virustotal virtual machine then one day I will donate to you

**Comment by samogost** [comment]
> try: pip uninstall cryptography pip install cryptography

ahh i finally got it, tell me how it works. How to anti-vm virustotal by this, how to insert this anti-vm into my virus?

**Comment by samogost** [comment]
> try: pip uninstall cryptography pip install cryptography

hey

**Comment by 6nz** [comment]
You can message me on discord

**Comment by 6nz** [comment]
Marci#0101
